FROM continuumio/miniconda3
RUN apt-get update
RUN apt-get install -y build-essential zlib1g zlib1g-dev
RUN mkdir /opt/build
COPY docker/install_with_conda.sh /opt/build
COPY py/ /opt/build/py/
COPY src/ /opt/build/src/
COPY falcon/ /opt/build/falcon/
RUN cd /opt/build; bash install_with_conda.sh
RUN . /opt/conda/bin/activate; conda clean --all

FROM continuumio/miniconda3
COPY --from=0 /opt/conda /opt/conda
RUN apt-get update
RUN apt-get install -y parallel time
RUN . /opt/conda/bin/activate; conda activate peregrine; python3 -m pip install cffi==1.12.2
RUN apt-get install -y make
RUN mkdir /opt/licenses
COPY docker/LICENSE /opt/licenses/LICENSE
COPY docker/LICENSE.falcon /opt/licenses/LICENSE.falcon
COPY docker/LICENSE.minimap2 /opt/licenses/LICENSE.minimap2
RUN mkdir /opt/test
COPY docker/test/Makefile /opt/test
COPY docker/test/run_test.sh /opt/test
COPY docker/test/simulate_reads.py /opt/test
COPY docker/bashrc /root/.bashrc
COPY docker/entry.sh /opt/
COPY docker/entry_dev.sh /opt/
WORKDIR /opt/test
ENTRYPOINT ["/opt/entry.sh"]
